# Generated by Django 4.1.7 on 2023-06-13 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comeing_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuyue_time', models.CharField(max_length=20, verbose_name='预约时间')),
                ('yueye_xingqi', models.CharField(max_length=20, verbose_name='预约日期')),
                ('now_people', models.IntegerField(default=1, verbose_name='当前人数')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('gym_name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='场馆名')),
                ('max_people', models.IntegerField(verbose_name='最大人数')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('student_chances', models.IntegerField(verbose_name='剩余次数')),
                ('student_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='学号')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='comeing_time',
            name='gym_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.gym', verbose_name='场馆名称'),
        ),
        migrations.AddField(
            model_name='comeing_time',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comeing_time_by_name', to='app01.student', verbose_name='学生姓名'),
        ),
        migrations.AddField(
            model_name='comeing_time',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comeing_time_by_number', to='app01.student', verbose_name='学号'),
        ),
    ]
